### ISSUE TITLE
The content resource fails validation

### ISSUE THREAD

**Issue by nigeltiany** [vietthang/hapi-boilerplate#2]
The content resource fails a validation check somewhere.
It could be the data field that saves an object.

```
[1] Debug: internal, implementation, error 
[1]     Error: Validation Error
[1]     at Object.responseFailAction [as failAction] (/home/nigel/Documents/hapi-boilerplate-master/node_modules/overjoy-swag/src/hapiIntegration.ts:60:14)
[1]     at request._protect.run (/home/nigel/Documents/hapi-boilerplate-master/node_modules/hapi/lib/validation.js:213:45)
[1]     at module.exports.internals.Protect.internals.Protect.run (/home/nigel/Documents/hapi-boilerplate-master/node_modules/hapi/lib/protect.js:62:12)
[1]     at postValidate (/home/nigel/Documents/hapi-boilerplate-master/node_modules/hapi/lib/validation.js:210:26)
[1]     at Hoek.once (/home/nigel/Documents/hapi-boilerplate-master/node_modules/hapi/lib/protect.js:52:16)
[1]     at wrapped (/home/nigel/Documents/hapi-boilerplate-master/node_modules/hapi/node_modules/hoek/lib/index.js:871:20)
[1]     at Object.validate (/home/nigel/Documents/hapi-boilerplate-master/node_modules/overjoy-swag/src/validate.ts:49:7)
[1]     at /home/nigel/Documents/hapi-boilerplate-master/node_modules/overjoy-swag/src/hapiIntegration.ts:80:51
[1]     at request._protect.run (/home/nigel/Documents/hapi-boilerplate-master/node_modules/hapi/lib/validation.js:239:16)
[1]     at module.exports.internals.Protect.internals.Protect.run (/home/nigel/Documents/hapi-boilerplate-master/node_modules/hapi/lib/protect.js:62:12)
[1]     at exports.response (/home/nigel/Documents/hapi-boilerplate-master/node_modules/hapi/lib/validation.js:237:22)
[1]     at each (/home/nigel/Documents/hapi-boilerplate-master/node_modules/hapi/lib/request.js:380:16)
[1]     at iterate (/home/nigel/Documents/hapi-boilerplate-master/node_modules/hapi/node_modules/items/lib/index.js:36:13)
[1]     at done (/home/nigel/Documents/hapi-boilerplate-master/node_modules/hapi/node_modules/items/lib/index.js:28:25)
[1]     at finalize (/home/nigel/Documents/hapi-boilerplate-master/node_modules/hapi/lib/handler.js:21:16)
[1]     at Hoek.once (/home/nigel/Documents/hapi-boilerplate-master/node_modules/hapi/lib/protect.js:52:16)
```

**Comment by nigeltiany** [comment]
Found the issue, nothing major. ```Additional Properties``` on the update route needs to be true because it is cascaded to the create route and the get route. https://github.com/vietthang/hapi-boilerplate/blob/06750951ec69b766a0730448d9d5564693daaca9/src/schemas/models/content.yaml#L26

https://github.com/vietthang/hapi-boilerplate/blob/06750951ec69b766a0730448d9d5564693daaca9/src/schemas/models/content.yaml#L30

https://github.com/vietthang/hapi-boilerplate/blob/06750951ec69b766a0730448d9d5564693daaca9/src/schemas/models/content.yaml#L42
